- type: replace
  path: /releases/-
  value:
    name: bosh-system-metrics-forwarder
    version: latest

- type: replace
  path: /instance_groups/-
  value:
    name: bosh-system-metrics-forwarder
    azs:
    - z1
    instances: 2
    persistent_disk_type: default
    vm_type: default
    stemcell: default
    networks:
    - name: default
    jobs:
    - name: metron_agent
      release: loggregator
      properties:
        doppler:
          addr:
        metron_agent:
          bosh_dns: true
          disable_udp: false
          deployment: loggregator
        loggregator:
          tls:
            ca_cert: "((loggregator_agent.ca))"
            metron:
              cert: "((loggregator_agent.certificate))"
              key: "((loggregator_agent.private_key))"
    - name: bosh-system-metrics-forwarder
      release: bosh-system-metrics-forwarder
      properties:
        bosh:
          url: "https://((internal_ip)):25555"
          root_ca_cert: "((director_ssl.ca))"
        metrics_server:
          addr: "((internal_ip)):25595"
        metrics_forwarder:
          envelope_ip_tag: "((internal_ip))"
          tls:
            ca_cert: "((system_metrics_server_ssl.ca))"
            common_name: "((internal_ip))"
        uaa_client:
          identity: "system_metrics_client"
          password: "((system_metrics_uaa_client_secret))"
        loggregator:
          ca_cert: "((loggregator_agent.ca))"
          cert: "((loggregator_agent.certificate))"
          key: "((loggregator_agent.private_key))"
    - name: indicator-registration-agent
      release: bosh-system-metrics-forwarder
      properties:
        indicator_registry_uri: indicator-registry.((system_domain))
    update:
      serial: true
      max_in_flight: 1
