#!/bin/bash

pushd src/github.com/cloudfoundry/bosh-system-metrics-forwarder
  go test -mod=vendor ./... -race -count 10
  exit_status=$?
popd

if [ $exit_status -ne 0 ]; then
  echo "TESTS FAILED!"
fi

exit $exit_status
