name: pull-request-ci
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: go vet ./...
        working-directory: src
      - run: go test -v -race ./...
        working-directory: src
